### ISSUE TITLE
Possibly unnecessary options

### ISSUE THREAD

**Issue by CrazyKidJack** [flacoman91/react-18-vector-grid-example#2]
@flacoman91 This is a continuation of the conversation on https://github.com/mhasbie/react-leaflet-vectorgrid/issues/16

In this code from your VectorGrid.js file
https://github.com/flacoman91/react-18-vector-grid-example/blob/d5e183c4936cdfee480056aab09a1bfe9c31e9ac/src/Leaflet/VectorGrid.js#L189-L211
Lines 194-203 I think are unnecessary. You said in the previous conversation that you

>  just copy pasted the example from https://github.com/Leaflet/Leaflet.VectorGrid#dependencies

but I can't find any example like that and those options are not documented in the [Leaflet.VectorGrid](https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html), [react-leaflet](https://react-leaflet.js.org/docs/api-map/), or [leaflet](https://leafletjs.com/reference.html) documentation.

I tried just commenting out those lines entirely and the application still works as expected. To be clear, if you change the current code to look like this, it still worked for me:
```js
const vectorGrid = useMemo( 
     () => { 
         const options = { 
             rendererFactory: L.svg.tile, 
             interactive: true, 
            /*
             style: { 
                 weight: 0.5, 
                 opacity: 1, 
                 color: '#ccc', 
                 fillColor: '#390870', 
                 fillOpacity: 0.6, 
                 fill: true, 
                 stroke: true 
             }, 
             type: 'protobuf', 
            */
             vectorTileLayerStyles: vectorTileStyling, 
             apikey: 'gCZXZglvRQa6sB2z7JzL1w' 
         }; 
  
         return L.vectorGrid.protobuf(nextzenTilesUrl, options) 
     }, 
     [nextzenTilesUrl, vectorTileStyling] 
 ); 
```

Lastly, even if you leave that code in, but modify it... it doesn't seem to change anything. For example, the following code renders a map that looks exactly the same as the current code:
```js
const vectorGrid = useMemo( 
     () => { 
         const options = { 
             rendererFactory: L.svg.tile, 
             interactive: true, 
             style: { 
                 weight: 5.0, //notice this changed
                 opacity: 1, 
                 color: '#000', //notice this changed
                 fillColor: '#000000', //notice this changed
                 fillOpacity: 0.6, 
                 fill: true, 
                 stroke: true 
             }, 
             type: 'anything', //notice this changed
             vectorTileLayerStyles: vectorTileStyling, 
             apikey: 'gCZXZglvRQa6sB2z7JzL1w' 
         }; 
  
         return L.vectorGrid.protobuf(nextzenTilesUrl, options) 
     }, 
     [nextzenTilesUrl, vectorTileStyling] 
 ); 
```

**Comment by flacoman91** [comment]
I remember those styles are used with Mapbox as a provider.  I think nothing seems to change because the tile service I've linked to might not have any relevant layers in it.

I need to create a personal account on mapbox with some demo data so you can see how it works.
https://docs.mapbox.com/help/tutorials/get-started-tokens-api/

**Comment by flacoman91** [comment]
You're right.  Thanks for continuing with looking at this!

 That was a mistake so I removed it.  Hopefully if someone else looks at this code they won't be confused. 

I added redux toolkit to the example with some buttons to toggle between mapbox and nextzen and checkboxes to hide/show features.
